#!/bin/sh

SIMPLEBADGE_CONTRACT="simplebadge"
GOTCHABADGE_CONTRACT="gotchabadge"
ORCHESTRATOR_CONTRACT="metadata"
AABADGE_CONTRACT="aabadge"
CUMULATIVE_CONTRACT="cumulative"
ROUNDS_CONTRACT="rounds"
ACCOUNT_PREFERENCES_CONTRACT="userprefs"


CLEOS_URL="http://127.0.0.1:8888/"

cmake . -DSIMPLEBADGE_CONTRACT=$SIMPLEBADGE_CONTRACT -DGOTCHABADGE_CONTRACT=$GOTCHABADGE_CONTRACT -DORCHESTRATOR_CONTRACT=$ORCHESTRATOR_CONTRACT -DAABADGE_CONTRACT=$AABADGE_CONTRACT -DCUMULATIVE_CONTRACT=$CUMULATIVE_CONTRACT -DROUNDS_CONTRACT=$ROUNDS_CONTRACT -DACCOUNT_PREFERENCES_CONTRACT=$ACCOUNT_PREFERENCES_CONTRACT 
eosio-cpp -abigen -I ./include -R ./resource -contract org -o org.wasm src/org.cpp

#cleos -u $CLEOS_URL set contract $ROUNDS_CONTRACT consumers/rounds rounds.wasm rounds.abi -p $ROUNDS_CONTRACT@active
#cleos -u $CLEOS_URL set account permission $ROUNDS_CONTRACT active --add-code -p $ROUNDS_CONTRACT@active
