#!/bin/sh

SIMPLEBADGE_CONTRACT="simplebadge1"
GOTCHABADGE_CONTRACT="gotchabadge1"
ORCHESTRATOR_CONTRACT="metadata1111"
AABADGE_CONTRACT="aabadge11111"
CUMULATIVE_CONTRACT="cumulative11"
ROUNDS_CONTRACT="rounds111111"
ACCOUNT_PREFERENCES_CONTRACT="userprefs111"
ORG_CONTRACT="org211111111"


CLEOS_URL="http://jungle4.cryptolions.io"

cmake . -DSIMPLEBADGE_CONTRACT=$SIMPLEBADGE_CONTRACT -DGOTCHABADGE_CONTRACT=$GOTCHABADGE_CONTRACT -DORCHESTRATOR_CONTRACT=$ORCHESTRATOR_CONTRACT -DAABADGE_CONTRACT=$AABADGE_CONTRACT -DCUMULATIVE_CONTRACT=$CUMULATIVE_CONTRACT -DROUNDS_CONTRACT=$ROUNDS_CONTRACT -DACCOUNT_PREFERENCES_CONTRACT=$ACCOUNT_PREFERENCES_CONTRACT 
eosio-cpp -abigen -I ./include -R ./resource -contract org -o org.wasm src/org.cpp

cleos -u $CLEOS_URL set contract $ORG_CONTRACT . org.wasm org.abi -p $ORG_CONTRACT@active
cleos -u $CLEOS_URL set account permission $ORG_CONTRACT active --add-code -p $ORG_CONTRACT@active
